# Generated by Django 3.2.9 on 2021-11-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingMediumContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.TextField()),
                ('img', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
